version: '3.8'

services: 
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=neil
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data